### PR TITLE
Several improvements related to CI and GitHub Actions

### PR DESCRIPTION
**Pull request by DilumAluthge**
This pull request makes the following changes:

1. Run GitHub Actions CI on both Linux and Windows 
2. Disable AppVeyor
3. README: add the GitHub Actions badge; delete the Travis badge; delete the AppVeyor badge
4. Update the TagBot configuration to the latest recommended configuration
5. When building the documentation, clone the General registry over Git - this ensures that we have access to the latest registered versions of all dependencies
6. Temporarily disable the doctests.

### CODE REVIEW

**Comment by chriselrod** [comment]
Awesome, this looks great!

Among the checks, I see:

> continuous-integration/appveyor/pr — AppVeyor build failed 

Why is this still there after removing Appveyor?

I updated a docstring for the new printing (`Vector{Operation}` instead of `Array{Operation,1}`) which caused a doctest failure. But do doctests happen on both versions? Would be good to have docs building again.

**Comment by chriselrod** [comment]
You labeled it a WIP; please let me know when it's good to merge.

Also, the nighly job completed quickly because REGISTER_COUNT=16, which means it unrolls much less.

**Comment by DilumAluthge** [comment]
> Among the checks, I see:
> 
> > continuous-integration/appveyor/pr — AppVeyor build failed
> 
> Why is this still there after removing Appveyor?

Ugh. AppVeyor. You have to log in to the AppVeyor website (https://ci.appveyor.com/project/chriselrod/LoopVectorization-jl) and disable or delete the `chriselrod/LoopVectorization-jl` project.

Once that's done, let me know - I'll push another commit to this branch to make sure AppVeyor is actually disabled.

**Comment by DilumAluthge** [comment]
> I updated a docstring for the new printing (`Vector{Operation}` instead of `Array{Operation,1}`) which caused a doctest failure. But do doctests happen on both versions? Would be good to have docs building again.

Let's try running doctests on `nightly` instead of `'1'`.

**Comment by DilumAluthge** [comment]
I moved the doctests to run on Julia nightly, and they are passing now!

**Comment by DilumAluthge** [comment]
Good to go now.

**Comment by chriselrod** [comment]
> Once that's done, let me know - I'll push another commit to this branch to make sure AppVeyor is actually disabled.

I clicked around on their website after making my comment and saw a "only run is there is an appveyor.yml file" and clicked that. Glad that it seems to have worked.

Thanks for the PR!

**Pull request merged**
