### PR TITLE
Try to fix a bug in code coverage

### PR DESCRIPTION
**Pull request by DilumAluthge**
This fixes https://github.com/JuliaLinearAlgebra/Octavian.jl/issues/15 for me locally

### CODE REVIEW

**Review by chriselrod — APPROVED** [review]
Looks good. I'll merge when tests pass.
I've been making some changes locally, and will issue a new release when I've finished them.

**Comment by DilumAluthge** [comment]
> Looks good. I'll merge when tests pass.
> I've been making some changes locally, and will issue a new release when I've finished them.

Let me do one last check to make sure it fixes the Octavian issue.

**Comment by DilumAluthge** [comment]
Yeah, I can confirm that this PR fixes https://github.com/JuliaLinearAlgebra/Octavian.jl/issues/15 for me locally.

With `LoopVectorization#master`:
```
        - """
        - The macrokernel. It iterates over our tiles, and applies the microkernel.
        - """
       17 function macrokernel!(C, A, B, α, β)
       17     iszero(β) && return macrokernel!(C, A, B, α, StaticInt{0}())
        0     LoopVectorization.@avx for n ∈ axes(C,2), m ∈ axes(C,1)
        1         Cmn = zero(eltype(C))
        1         for k ∈ axes(B,1)
        1             Cmn += A[m,k] * B[k,n]
        -         end
        -         # C[m,n] may be `NaN`, but if `β == 0` we still want to zero it
        1         C[m,n] = (α * Cmn) + β * C[m,n]
        -     end
        - end
       16 function macrokernel!(C, A, B, α, ::StaticInt{0})
       16     LoopVectorization.@avx for n ∈ axes(C,2), m ∈ axes(C,1)
       16         Cmn = zero(eltype(C))
       16         for k ∈ axes(B,1)
       16             Cmn += A[m,k] * B[k,n]
        -         end
        -         # C[m,n] may be `NaN`, but if `β == 0` we still want to zero it
       16         C[m,n] = (α * Cmn)
        -     end
        - end
```

With this PR branch:
```
        - """
        - The macrokernel. It iterates over our tiles, and applies the microkernel.
        - """
       17 function macrokernel!(C, A, B, α, β)
       17     iszero(β) && return macrokernel!(C, A, B, α, StaticInt{0}())
        1     LoopVectorization.@avx for n ∈ axes(C,2), m ∈ axes(C,1)
        1         Cmn = zero(eltype(C))
        1         for k ∈ axes(B,1)
        1             Cmn += A[m,k] * B[k,n]
        -         end
        -         # C[m,n] may be `NaN`, but if `β == 0` we still want to zero it
        1         C[m,n] = (α * Cmn) + β * C[m,n]
        -     end
        - end
       16 function macrokernel!(C, A, B, α, ::StaticInt{0})
       32     LoopVectorization.@avx for n ∈ axes(C,2), m ∈ axes(C,1)
       16         Cmn = zero(eltype(C))
       16         for k ∈ axes(B,1)
       16             Cmn += A[m,k] * B[k,n]
        -         end
        -         # C[m,n] may be `NaN`, but if `β == 0` we still want to zero it
       16         C[m,n] = (α * Cmn)
        -     end
        - end
```

**Comment by DilumAluthge** [comment]
This should be good to go once CI passes.

**Comment by chriselrod** [comment]
Great, looks good!

**Comment by baggepinnen** [comment]
Sorry for hijacking this conversation, but it appears that `RecipesBase.@recipe` is having the same issue
https://codecov.io/gh/baggepinnen/MatrixProfile.jl/src/master/src/plotting.jl
I tried to understand your solution in this PR and adopt it by adding 
```
$(__source__)
```
to the line below
https://github.com/JuliaPlots/RecipesBase.jl/blob/21ebce5df7a19c5097ddac79a224b1503d02cc8e/src/RecipesBase.jl#L274
but it does not appear to have helped. Do you have insight into what is required to fix this, and perhaps why it arises in the forst place?

**Comment by chriselrod** [comment]
@baggepinnen 
The problem is that `LineNumberNode`s are needed for code coverage. I don't know about `RecipesBase`, but LoopVectorization does not save these line number nodes from the original source (note that `LoopVectorization` does not use `Expr` objects to represent loops internally; the original `Expr` is parsed and then discarded).
In the future, I'll add a field to the internal data structures storing `LineNumberNode`s so that when it finally creates a new `Expr`, it'll be able to insert `LineNumberNode`s at reasonably representative locations.

For now, the work around is to just dump all the `LineNumberNode`s from the original `Expr` at the front of the macro expansion in front of `nothing`s (if they follow one another without the `nothing`s, they don't get counted). For example, in this 5-line loop (`end`s don't count toward coverage) defined in the REPL, the nodes `#= REPL[16]:1 =#` through `#= REPL[16]:5 =#` get placed at the front:
```julia
julia> using LoopVectorization

julia> @macroexpand @avx for i ∈ eachindex(x,y)
           xᵢ² = x[i]^2
           nhxᵢ² = -0.5*xᵢ²
           expnxᵢ² = exp(nhxᵢ²)
           y[i] = expnxᵢ²
       end
quote
    begin
        #= REPL[16]:5 =#
        nothing
    end
    begin
        #= REPL[16]:4 =#
        nothing
    end
    begin
        #= REPL[16]:3 =#
        nothing
    end
    begin
        #= REPL[16]:2 =#
        nothing
    end
    begin
        #= REPL[16]:1 =#
        nothing
    end
    begin
        var"###looprangei###1###" = LoopVectorization.canonicalize_range(eachindex(x, y))
        var"###loopleni###2###" = LoopVectorization.maybestaticlength(var"###looprangei###1###")
        var"###i_loop_lower_bound###3###" = LoopVectorization.maybestaticfirst(var"###looprangei###1###")
        var"###i_loop_upper_bound###4###" = LoopVectorization.maybestaticlast(var"###looprangei###1###")
    end
    if LoopVectorization.check_args(x, y)
        var"##vptr##_x" = LoopVectorization.stridedpointer(x)
        var"##vptr##_y" = LoopVectorization.stridedpointer(y)
        begin
            var"##x#245" = LoopVectorization.preserve_buffer(x)
            var"##y#246" = LoopVectorization.preserve_buffer(y)
            $(Expr(:gc_preserve, quote
    begin
        var"##Tloopeltype##" = LoopVectorization.promote_type(LoopVectorization.eltype(x), LoopVectorization.eltype(y))
        var"##Wvecwidth##" = LoopVectorization.pick_vector_width_val(LoopVectorization._eltype(x), LoopVectorization._eltype(y))
    end
    LoopVectorization._avx_!(Val{(0, 0, 0, LoopVectorization.unwrap(var"##Wvecwidth##"))}(), Tuple{:LoopVectorization, :getindex, LoopVectorization.OperationStruct(0x0000000000000001, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, LoopVectorization.memload, 0x01, 0x01), :LoopVectorization, :abs2, LoopVectorization.OperationStruct(0x0000000000000001, 0x0000000000000000, 0x0000000000000000, 0x0000000000000001, LoopVectorization.compute, 0x00, 0x02), :LoopVectorization, :LOOPCONSTANTINSTRUCTION, LoopVectorization.OperationStruct(0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, LoopVectorization.constant, 0x00, 0x03), :LoopVectorization, :*, LoopVectorization.OperationStruct(0x0000000000000001, 0x0000000000000000, 0x0000000000000000, 0x0000000000000302, LoopVectorization.compute, 0x00, 0x04), :LoopVectorization, :exp, LoopVectorization.OperationStruct(0x0000000000000001, 0x0000000000000000, 0x0000000000000000, 0x0000000000000004, LoopVectorization.compute, 0x00, 0x05), :LoopVectorization, :setindex!, LoopVectorization.OperationStruct(0x0000000000000001, 0x0000000000000000, 0x0000000000000000, 0x0000000000000005, LoopVectorization.memstore, 0x02, 0x06)}, Tuple{LoopVectorization.ArrayRefStruct{:x, Symbol("##vptr##_x")}(0x0000000000000001, 0x0000000000000001, 0x0000000000000000), LoopVectorization.ArrayRefStruct{:y, Symbol("##vptr##_y")}(0x0000000000000001, 0x0000000000000001, 0x0000000000000000)}, Tuple{0, Tuple{}, Tuple{}, Tuple{}, Tuple{(3, -0.5)}, Tuple{}, Tuple{}}, Tuple{:i}, (var"###looprangei###1###",), var"##vptr##_x", var"##vptr##_y")
    nothing
end, Symbol("##x#245"), Symbol("##y#246")))
        end
    else
        $(Expr(:inbounds, true))
        local var"#17#val" = for i = eachindex(x, y)
                    #= REPL[16]:2 =#
                    xᵢ² = Base.FastMath.pow_fast(x[i], Val{2}())
                    #= REPL[16]:3 =#
                    nhxᵢ² = Base.FastMath.mul_fast(-0.5, xᵢ²)
                    #= REPL[16]:4 =#
                    expnxᵢ² = Base.FastMath.exp_fast(nhxᵢ²)
                    #= REPL[16]:5 =#
                    y[i] = expnxᵢ²
                end
        $(Expr(:inbounds, :pop))
        var"#17#val"
    end
end
```
This way, when your code gets run in a test suite, it'll register as covered.
Note that nodes 2-5 also appear in the fallback `@fastmath` loop, but apparently node 1 (corresponding to the `eachindex`) gets stripped. It should probably be added there as well. Although either way, code coverage won't really give you an indication of whether the `_avx_!` or fallback loop was run.

**Pull request merged**
